### ISSUE TITLE
String identifiers for materials and boundaries

### ISSUE THREAD

**Issue by latug0** [thelfer/mfem-mgis#40]
The final user imports a mesh at the beginning of each numerical simulation.
MFEM typically deals with material ids and boundary ids, but these are integers and are not very pratical to deal with because user has to remind exactly which identifier is associated with each material/boundary.
We would like a support for using string identifiers in the input parameters and postprocessing to simplify user's life to replace integer ids.
This could be well coordinated with MED support that provides such kind of string references.
Remark : GMSH reader of MFEM will typically not retrieve the information of string idenftifiers from the mesh (it would require much work to do this addtionnal feature), we will not target for the moment to have extended suppor to read string identifiers from GMSH files.

**Comment by thelfer** [comment]
@latug0 Would you check if MED imposes unique identifiers for all the groups in the mesh, i.e. the same identifier can't be used for  a boundary and a domain (a domain is defined here as a set of volumes in 3D).

Also, MED also supports groups gathering multiple materials. This may also be convenient for post-processing.

**Comment by thelfer** [comment]
A new branch named `th/string_identifiers_for_materials_and_boundaries` has been introduced to treat this issue.

# Proposed API

The `FiniteElementDiscretization` which contains the `MFEM` mesh object seems the appropriate place to hold mesh names.

The following methods has been introduced in the 

- `setMaterialsNames` which allows to specifiy a mapping between the mesh attributes and names.
- `setBoundariesNames`  which allows to specifiy a mapping between the mesh boundaries attributes and names.

Names are restricted to be valid C++ identifiers (i.e. may contains A-Z, a-z, 0-9, '_'  characters and shall not start with a digit).

Two methods, `getMaterialsIdentifiers` and `getBoundariesIdentifiers`, have been introduced to retrieve the list of identifiers associated with a parameter. The parameter may hold an integer, a string or a vector of parameters which must be either strings and integers. Integers are directly intepreted as attributes. Strings are intepreted as regular expressions which allows the selection by names.

For convenience, the `NonlinearEvolutionProblem` and  `NonlinearEvolutionProblemImplementations` classes also provide all the previous methods (`setMaterialsNames`, `setBoundariesNames`, `getMaterialsIdentifiers` and `getBoundariesIdentifiers`.

# Example of usage

```c++
  mfem_mgis::NonLinearEvolutionProblem p(
        {{"MeshFileName", parameters.mesh_file},
         {"FiniteElementFamily", "H1"},
         {"FiniteElementOrder", 2},
         {"UnknownsSize", 3}, {"Hypothesis", "Tridimensional"},
         {"Parallel", false}});
p.setMaterialsNames({{1, "Fuel"}, {2, "InnerCladding"}, {2, "OuterCladding"}});
const auto ids = `p.getMaterialsIdentifiers(".*Cladding.*");`
```

**Comment by thelfer** [comment]
The `addBehavourIntegrator` now takes a parameter rather than an integer. This is backward compatible as a Parameter can be implicitly build from an integer.

The `ParaviewExportIntegrationPointResultsAtNodes` class now supports defining materials by names. IMHO, the code is now quite nice and explicit:

```c++
    // if Materials exists, use it, otherwise, take all materials
    this->materials_identifiers =
        p.getMaterialsIdentifiers(get_if(params, "Materials", ".+"));
```
