### ISSUE TITLE
Using HypreILU

### ISSUE THREAD

**Issue by rprat-pro** [thelfer/mfem-mgis#59]
HypreILU is automatically disabled by the compilation flag: `-DHYPRE_OLD_VERSION`

This option is defined in CMakeLists.txt:15 and I can confirm that this option works as expected ... 

```
# HypreILU is not defined for old versions of Hypre
# Comment this line for newest Hypre librarires
ADD_DEFINITIONS(-DHYPRE_OLD_VERSION)
```

Regarding MFEM, we check that the Hypre version is recent, ie hypre >= 2.19v (code below).
mfem/linalg/hypre.cpp: 

```
#if MFEM_HYPRE_VERSION >= 21900
HypreILU::HypreILU()
{
   HYPRE_ILUCreate(&ilu_precond);
   SetDefaultOptions();
}
etc...
```

So, if  `HYPRE_OLD_VERSION` is only used to handle the use of HypreILU, we could do the code below, right? Or did I miss something again?  

```
if(HYPRE_VERSION VERSION_LESS 2.19) # HYPRE_VERSION env variable
ADD_DEFINITIONS(-DHYPRE_OLD_VERSION)
message(STATUS "HypreILU is disabled")
else()
message(STATUS "youpi, tu peux utiliser HypreILU")
endif()

```

Raphaël

**Comment by thelfer** [comment]
@rprat-pro HyperILU is always available if we compile mfem using spack, right ?
If so, the better is probably to remove completly references to this flag.

**Comment by rprat-pro** [comment]
It depends on your version of spack, but yes, even for the "old" spack version 0.16.1, the preferred version of hypre is 2.20.0 .

I dunno if someone uses an older hypre as an external package.

**Comment by thelfer** [comment]
Then I would drop this flag.
