### ISSUE TITLE
Using HypreDiagScale preconditioner

### ISSUE THREAD

**Issue by rprat-pro** [thelfer/mfem-mgis#60]
MFEM proposes to use the HypreDiagScale preconditioner that is just a Jacobi preconditioner in hypre. Among Hypre preconditioners, this is the only one with "identity" (useless I guess) that is not implemented in MFEM-MGIS.

Is it because it's a pretty simple preconditioner? Since I do a performance analysis for all solvers/preconditioners, even though I don't expected anything with such a preconditioner, I was wondering if it was voluntary.

**Comment by thelfer** [comment]
@rprat-pro I don't think that we did that intentionnaly. Do not hesitate to add it.

**Comment by rprat-pro** [comment]
Yes, I'm gonna add it.

Thank you.
