### ISSUE TITLE
Prepare first release

### ISSUE THREAD

**Issue by thelfer** [thelfer/mfem-mgis#89]
- Based on specific versions of TFEL (4.2), MGIS (2.2) and MFEM

TODO:

- Add release notes
- Modifiy the `spack` recipe

**Comment by rprat-pro** [comment]
move spack_repo into an external github repository.

**Comment by rprat-pro** [comment]
Add mgis-span

**Comment by thelfer** [comment]
- Register to [Zenodo](https://zenodo.org)

**Comment by rprat-pro** [comment]
What is done in PR #90 (branch rliv-1.0) : 
- Modifiy the `spack` recipe
  - tfel 4.2.1
  - mgis 2.2
  - add mumps
  - force suite-sparse 
- Adapt installation documentation
- Adapt code for `mgis` 2.2. (`mgis::span`)
- move spack_repo into an external github repository.

What remains to be done: 
- Adapt mfem-mgis-example (mgis2.2) 
- Register to [Zenodo](https://zenodo.org/)

**Comment by rprat-pro** [comment]
Adapt mfem-mgis-example (mgis2.2) -> After discussion, we will keep the master version of mgis
Register to Zenodo [DONE] -> https://zenodo.org/records/13171969
Write changelog [DONE]

I close this issue, @thelfer @maxence-wz 
Feel free to reopen it if you wanna complete it.
